# Generated by Django 6.0 on 2025-12-07 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charlas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charla',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['ADMIN', 'SUPERVISOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='charlas_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
