# Generated by Django 6.0 on 2025-12-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charla',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo adjunto (PDF, DOCX, PPT)', null=True, upload_to='media/charlas'),
        ),
    ]
