# Generated by Django 6.0 on 2025-12-22 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_initial'),
        ('charlas', '0003_charla_archivo_adjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charla',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'En Repertorio'), ('ENVIADA', 'Enviada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='charla',
            name='firmas',
            field=models.ManyToManyField(blank=True, related_name='charlas_firmadas', through='asistencias.Asistencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
