# Generated by Django 6.0 on 2025-12-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_upervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='upervisor',
            new_name='supervisor',
        ),
    ]
