# Generated by Django 6.0 on 2025-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_firma', models.DateTimeField(auto_now_add=True)),
                ('firma_hash', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-hora_firma'],
            },
        ),
    ]
