# Generated by Django 6.0 on 2025-12-07 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencias', '0001_initial'),
        ('charlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='charla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='charlas.charla'),
        ),
    ]
