# Generated by Django 6.0 on 2025-12-07 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('url_pdf', models.URLField(blank=True, max_length=500)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('charla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='charlas.charla')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
