# Generated by Django 6.0 on 2025-12-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Control de Acceso',
                'verbose_name_plural': 'Controles de Acceso',
                'ordering': ['-hora_entrada'],
            },
        ),
    ]
